#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo "## eslint view #################"
yarn lint:view
echo "\n\n## eslint fix #################"
yarn lint:fix
echo "\n\n## eslint view #################"
yarn lint:view
echo "\n\n## format prettier #################"
yarn format:write
